# Generated by Django 5.1.5 on 2025-02-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order'),
    ]

    operations = [
    ]
