# Generated by Django 5.1.5 on 2025-03-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_payment_id_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment')], default='Online', max_length=20),
            preserve_default=False,
        ),
    ]
